resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

shared:
- params: &om-creds
    OM_USERNAME: ((Shared-Paving Terraform/ci/om/Notes/username))
    OM_PASSWORD: ((Shared-Paving Terraform/ci/om/Notes/password))

resources:
- name: env-state-gcp
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: infra-2-tf-states
      prefix: gcp
      credentials: ((Shared-Paving Terraform/ci/cf_infra_2_gcp_service_account_key/Notes))
    vars:
      environment_name: paving-gcp
      project: ((Shared-Paving Terraform/ci/cf_infra_2_gcp_project_id/Notes))
      region: us-east1
      availability_zones: ["us-east1-b", "us-east1-c",  "us-east1-d"]
      hosted_zone: ((Shared-Paving Terraform/ci/cf_infra_2_hosted_zone/Notes))
      service_account_key: ((Shared-Paving Terraform/ci/cf_infra_2_gcp_service_account_key/Notes))
      ssl_certificate: ((Shared-Paving Terraform/ci/terraforming-gcp/Notes/certificate))
      ssl_private_key: ((Shared-Paving Terraform/ci/terraforming-gcp/Notes/private_key))

- name: paving
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal/paving.git
    private_key: ((Shared-Paving Terraform/ci/paving_pas_deploy_key/Notes/private_key))
    # paths:
    # - "gcp/*"
    ignore_paths:
    - "ci/*"

- name: paving-ci
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal/paving.git
    private_key: ((Shared-Paving Terraform/ci/paving_pas_deploy_key/Notes/private_key))
    paths:
    - "ci/*"

- name: pcf-releng-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-releng-ci.git
    private_key: ((Shared-Paving Terraform/ci/cf_infra_bot_github_user/Notes/private_key))
    ignore_paths:
    - pipelines
    - ci_screen

- name: srt
  type: pivnet
  source:
    api_token: ((Shared-Paving Terraform/ci/pivnet_token/Notes))
    product_slug: elastic-runtime
    product_version: 2.8.\d+
    sort_by: semver

- name: pks
  type: pivnet
  source:
    api_token: ((Shared-Paving Terraform/ci/pivnet_token/Notes))
    product_slug: pivotal-container-service
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: opsman-image
  type: pivnet
  source:
    product_slug: ops-manager
    api_token: ((Shared-Paving Terraform/ci/pivnet_token/Notes))
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((Shared-Paving Terraform/ci/aws_access_key_id/Notes))
    secret_access_key: ((Shared-Paving Terraform/ci/aws_secret_access_key/Notes))
    bucket: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket/Notes))
    region_name: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket_region/Notes))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((Shared-Paving Terraform/ci/aws_access_key_id/Notes))
    secret_access_key: ((Shared-Paving Terraform/ci/aws_secret_access_key/Notes))
    bucket: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket/Notes))
    region_name: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket_region/Notes))
    regexp: platform-automation-image-(.*).tgz

jobs:
- name: paving-gcp
  old_name: deploy-gcp
  serial: true
  serial_groups: [gcp]
  public: false
  plan:
  - in_parallel:
    - get: paving
    - get: paving-ci
    - get: pcf-releng-ci
    - get: srt
      params:
        globs:
        - srt-*.pivotal
    - get: pks
      params:
        globs:
        - pivotal-container-service-*.pivotal
    - get: opsman-image
      params:
        globs:
        - '*gcp*.yml'
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true

  - do:

    - in_parallel:
      - task: download-srt-stemcell
        file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
        input_mapping:
          ert-product: srt
        output_mapping:
          stemcell: stemcell-srt
        params:
          IAAS_TYPE: gcp
          PIVNET_TOKEN: ((Shared-Paving Terraform/ci/pivnet_token/Notes))

      - task: download-pks-stemcell
        file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
        input_mapping:
          ert-product: pks
        output_mapping:
          stemcell: stemcell-pks
        params:
          IAAS_TYPE: gcp
          PIVNET_TOKEN: ((Shared-Paving Terraform/ci/pivnet_token/Notes))

    - put: env-state-gcp
      params:
        env_name: paving-gcp
        terraform_source: paving/gcp
        delete_on_failure: true

    - task: get-ops-manager-config
      file: paving-ci/ci/tasks/get-ops-manager-config/task.yml
      input_mapping:
        env-state: env-state-gcp
        paving: paving-ci
      output_mapping:
        env-state: env-state-gcp
      params:
        IAAS: gcp
        GCP_SERVICE_ACCOUNT_KEY: ((Shared-Paving Terraform/ci/cf_infra_2_gcp_service_account_key/Notes))

    - task: create-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/create-vm.yml
      input_mapping:
        image: opsman-image
        state: env-state-gcp
      params:
        OPSMAN_CONFIG_FILE: ops-manager.yml
      on_failure:
        task: delete-vm
        image: platform-automation-image
        file: platform-automation-tasks/tasks/delete-vm.yml
        input_mapping:
          state: generated-state
        params:
          OPSMAN_CONFIG_FILE: ops-manager.yml

    - task: write-om-files
      file: paving-ci/ci/tasks/write-om-files/task.yml
      input_mapping:
        env-state: env-state-gcp
      params:
        <<: *om-creds
        AUTH_CONFIG_FILE: paving-ci/ci/configuration/auth.yml
        ENV_YML: paving-ci/ci/configuration/env.yml
        DIRECTOR_CONFIG_PATH: paving-ci/ci/configuration/gcp/director.yml
        SRT_CONFIG_FILE: paving-ci/ci/configuration/gcp/srt.yml
        PKS_CONFIG_FILE: paving-ci/ci/configuration/gcp/pks.yml

    - task: configure-authentication
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-authentication.yml

    - task: configure-director
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-director.yml

    - task: upload-srt-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        stemcell: stemcell-srt

    - task: upload-and-stage-srt
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      input_mapping:
        product: srt

    - task: configure-srt
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      params:
        CONFIG_FILE: srt.yml
      input_mapping:
        product: srt

    - task: upload-pks-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        stemcell: stemcell-pks

    - task: upload-and-stage-pks
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      input_mapping:
        product: pks

    - task: configure-pks
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      params:
        CONFIG_FILE: pks.yml
      input_mapping:
        product: pks

    - task: apply-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-changes.yml

    - task: delete-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/delete-installation.yml

    - task: delete-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/delete-vm.yml
      input_mapping:
        state: generated-state
      params:
        OPSMAN_CONFIG_FILE: ops-manager.yml

    - put: env-state-gcp
      params:
        terraform_source: paving/gcp
        env_name_file: env-state-gcp/name
        delete_on_failure: true
        action: destroy
      get_params:
        action: destroy

- name: cleanup-gcp
  serial: true
  public: false
  plan:
  - in_parallel:
    - get: paving-ci
    - get: paving
    - get: env-state-gcp
  - do:
    - task: leftovers
      file: paving-ci/ci/tasks/leftovers/task.yml
      input_mapping:
        env-state: env-state-gcp
      params:
        IAAS: gcp
    - put: env-state-gcp
      params:
        terraform_source: paving/gcp
        env_name_file: env-state-gcp/name
        delete_on_failure: true
        action: destroy
      get_params:
        action: destroy
