product-name: apmPostgres
network-properties:
  network:
    name: pas
  other_availability_zones:
  - name: ((availability_zones.0))
  - name: ((availability_zones.1))
  - name: ((availability_zones.2))
  singleton_availability_zone:
    name: ((availability_zones.0))
resource-config:
  redis:
    persistent_disk:
      size_mb: '51200'
  mysql:
    persistent_disk:
      size_mb: '51200'
    instance_type:
      id: 'automatic'
  postgres:
    instance_type:
      id: 'automatic'