product-name: harbor-container-registry
product-properties:
  .properties.hostname:
    value: harbor.((environment_name)).((hosted_zone))
  .properties.server_cert_key:
    value:
      cert_pem: |
        ((ssl_certificate))
      private_key_pem: |
        ((ssl_private_key))
  .properties.admin_password:
    value:
      secret: VMware1!
network-properties:
  network:
    name: management
  service_network:
    name: services
  other_availability_zones:
    - name: Availability Sets
  singleton_availability_zone:
    name: Availability Sets
resource-config:
  harbor-app:
    additional_vm_extensions:
      - harbor-lb-security-groups
    elb_names:
    - ((environment_name))-harbor-web-lb
