product-name: Pivotal_Single_Sign-On_Service
network-properties:
  network:
    name: pas
  service_network:
    name: services
  other_availability_zones:
  - name: ((availability_zones.0))
  - name: ((availability_zones.1))
  - name: ((availability_zones.2))
  singleton_availability_zone:
    name: ((availability_zones.0))
