---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools

inputs:
- name: env-state
- name: paving

outputs:
- name: env-state
- name: config

run:
  path: paving/ci/tasks/get-ops-manager-config/task

params:
  IAAS:

  GCP_SERVICE_ACCOUNT_KEY:
