---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalcfreleng/infrastructure

inputs:
- name: env-state
- name: paving-ci

params:
  # aws | gcp | azure
  IAAS:

run:
  path: paving-ci/ci/tasks/leftovers/task
