product-name: pivotal-container-service
network-properties:
  network:
    name: pks
  other_availability_zones:
  - name: Availability Sets
  service_network:
    name: services
  singleton_availability_zone:
    name: Availability Sets
product-properties:
  .pivotal-container-service.pks_tls:
    value:
      cert_pem: |
        ${var.ssl_certificate}
      private_key_pem: |
        ${var.ssl_private_key}
  .properties.cloud_provider:
    value: Azure
  .properties.cloud_provider.azure.azure_cloud_name:
    value: AzurePublicCloud
  .properties.cloud_provider.azure.default_security_group:
    value: ${var.platform_vms_security_group_name}
  .properties.cloud_provider.azure.location:
    value: ${var.location}
  .properties.cloud_provider.azure.primary_availability_set:
    value: ${var.pks_as_name}
  .properties.cloud_provider.azure.resource_group_name:
    value: ${var.resource_group_name}
  .properties.cloud_provider.azure.subscription_id:
    value: ${var.subscription_id}
  .properties.cloud_provider.azure.tenant_id:
    value: ${var.tenant_id}
  .properties.cloud_provider.azure.vnet_name:
    value: ${var.network_name}
  .properties.cloud_provider.azure.vnet_resource_group_name:
    value: ${var.environment_name}
  .properties.cloud_provider.azure.azure_master_managed_identity:
    value: ${var.pks_master_managed_identity}
  .properties.cloud_provider.azure.azure_worker_managed_identity:
    value: ${var.pks_worker_managed_identity}
  .properties.log_sink_resources_deploy:
    value: true
  .properties.metric_sink_resources_deploy:
    value: true
  .properties.pks_api_hostname:
    value: ${var.pks_dns}
  .properties.plan1_selector.active.master_az_placement:
    value:
    - Availability Sets
  .properties.plan1_selector.active.worker_az_placement:
    value:
    - Availability Sets
  .properties.plan1_selector.active.worker_instances:
    value: 3
  .properties.oidc_selector:
    value: disabled
  .properties.telemetry_selector:
    value: disabled
  .properties.telemetry_installation_purpose_selector:
    value: not_provided
resource-config:
  pivotal-container-service:
    additional_vm_extensions:
    - pks-api-lb-security-groups
    elb_names:
    - ${var.pks_lb_name}
