---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfinfrastructure/releng-tools

inputs:
- name: env-state
- name: paving-ci
- name: config

outputs:
- name: env
- name: config

params:
  OM_USERNAME:
  OM_PASSWORD:

  AUTH_CONFIG_FILE:
  ENV_YML:
  DIRECTOR_CONFIG_PATH:
  SRT_CONFIG_FILE:
  PKS_CONFIG_FILE:

run:
  path: paving-ci/ci/tasks/write-om-files/task
