---
network-assignment:
  network:
    name: management
  singleton_availability_zone:
    name: 'zone-1'
  other_availability_zones:
    name: 'zone-2'
networks-configuration:
  icmp_checks_enabled: false
  networks:
  - name: management
    service_network: false
    subnets:
    - iaas_identifier: ${var.network_name}/${var.management_subnet_name}
      cidr: ${var.management_subnet_cidr}
      reserved_ip_ranges: ${var.management_subnet_gateway}-${var.management_subnet_range}
      dns: 168.63.129.16
      gateway: ${var.management_subnet_gateway}
  - name: pas
    service_network: false
    subnets:
    - iaas_identifier: ${var.network_name}/${var.pas_subnet_name}
      cidr: ${var.pas_subnet_cidr}
      reserved_ip_ranges: ${var.pas_subnet_gateway}-${var.pas_subnet_range}
      dns: 168.63.129.16
      gateway: ${var.pas_subnet_gateway}
  - name: pks
    service_network: false
    subnets:
    - iaas_identifier: ${var.network_name}/${var.pks_subnet_name}
      cidr: ${var.pks_subnet_cidr}
      reserved_ip_ranges: ${var.pks_subnet_gateway}-${var.pks_subnet_range}
      dns: 168.63.129.16
      gateway: ${var.pks_subnet_gateway}
  - name: services-1
    service_network: false
    subnets:
    - iaas_identifier: ${var.network_name}/${var.services_subnet_name}
      cidr: ${var.services_subnet_cidr}
      reserved_ip_ranges: ${var.services_subnet_gateway}-${var.services_subnet_range}
      dns: 168.63.129.16
      gateway: ${var.services_subnet_gateway}
properties-configuration:
  iaas_configuration:
    subscription_id: ${var.subscription_id}
    tenant_id: ${var.tenant_id}
    client_id: ${var.client_id}
    client_secret: ${var.client_secret}
    resource_group_name: ${var.resource_group_name}
    bosh_storage_account_name: ${var.bosh_storage_account_name}
    default_security_group: ${var.platform_vms_security_group_name}
    ssh_public_key: ${var.ops_manager_ssh_public_key}
    ssh_private_key: ${var.ops_manager_ssh_private_key}
    cloud_storage_type: managed_disks
    storage_account_type: Standard_LRS
    environment: ${var.iaas_configuration_environment_azurecloud}
    availability_mode: availability_sets
  director_configuration:
    ntp_servers_string: 0.pool.ntp.org
    metrics_ip: ''
    resurrector_enabled: true
    post_deploy_enabled: false
    bosh_recreate_on_next_deploy: false
    retry_bosh_deploys: true
    hm_pager_duty_options:
      enabled: false
    hm_emailer_options:
      enabled: false
    blobstore_type: local
    database_type: internal
  security_configuration:
    trusted_certificates: ''
    generate_vm_passwords: true
vmextensions-configuration:
  - name: pks-api-lb-security-groups
    cloud_properties:
      security_group: ${var.pks_api_network_security_group_name}
      application_security_groups: ["${var.pks_api_application_security_group_name}"]
