resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

shared:
- params: &om-creds
    OM_USERNAME: ((Shared-Paving Terraform/ci/om/Notes/username))
    OM_PASSWORD: ((Shared-Paving Terraform/ci/om/Notes/password))

resources:
- name: env-state-aws
  type: terraform
  source:
    backend_type: gcs
    backend_config:
      bucket: infra-tf-states
      prefix: aws
      credentials: ((Shared-Paving Terraform/ci/cf_infra_gcp_service_account_key/Notes))
    vars:
      environment_name: paving-aws
      region: us-east-2
      access_key: ((Shared-Paving Terraform/ci/aws_access_key_id/Notes))
      secret_key: ((Shared-Paving Terraform/ci/aws_secret_access_key/Notes))
      availability_zones: ["us-east-2a", "us-east-2b", "us-east-2c"]
      hosted_zone: aws.infrastructure.cf-app.com
      ssl_certificate: ((Shared-Paving Terraform/ci/terraforming-aws/Notes/certificate))
      ssl_private_key: ((Shared-Paving Terraform/ci/terraforming-aws/Notes/private_key))
    env:
      AWS_ACCESS_KEY_ID: ((Shared-Paving Terraform/ci/aws_access_key_id/Notes))
      AWS_SECRET_ACCESS_KEY: ((Shared-Paving Terraform/ci/aws_secret_access_key/Notes))
      AWS_DEFAULT_REGION: us-east-2

- name: paving
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal/paving.git
    private_key: ((Shared-Paving Terraform/ci/paving_pas_deploy_key/Notes/private_key))
    ignore_paths:
    - "ci/*"

- name: paving-ci
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal/paving.git
    private_key: ((Shared-Paving Terraform/ci/paving_pas_deploy_key/Notes/private_key))
    paths:
    - "ci/*"

- name: pcf-releng-ci
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-releng-ci.git
    private_key: ((Shared-Paving Terraform/ci/cf_infra_bot_github_user/Notes/private_key))
    ignore_paths:
    - pipelines
    - ci_screen

- name: srt
  type: pivnet
  source:
    api_token: ((Shared-Paving Terraform/ci/pivnet_token/Notes))
    product_slug: elastic-runtime
    product_version: 2.8.\d+
    sort_by: semver

- name: srt-stemcell
  type: pivnet
  source:
    api_token: ((Shared-Paving Terraform/ci/pivnet_token/Notes))
    product_slug: stemcells-ubuntu-xenial
    product_version: ^621\.\d+
    sort_by: semver

- name: pks
  type: pivnet
  source:
    api_token: ((Shared-Paving Terraform/ci/pivnet_token/Notes))
    product_slug: pivotal-container-service
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: opsman-image
  type: pivnet
  source:
    product_slug: ops-manager
    api_token: ((Shared-Paving Terraform/ci/pivnet_token/Notes))
    product_version: ^\d+\.\d+\.\d+
    sort_by: semver

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((Shared-Paving Terraform/ci/aws_access_key_id/Notes))
    secret_access_key: ((Shared-Paving Terraform/ci/aws_secret_access_key/Notes))
    bucket: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket/Notes))
    region_name: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket_region/Notes))
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((Shared-Paving Terraform/ci/aws_access_key_id/Notes))
    secret_access_key: ((Shared-Paving Terraform/ci/aws_secret_access_key/Notes))
    bucket: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket/Notes))
    region_name: ((Shared-Paving Terraform/ci/s3_platform_automation_bucket_region/Notes))
    regexp: platform-automation-image-(.*).tgz


jobs:
- name: deploy-aws
  serial: true
  public: false
  plan:
  - in_parallel:
    - get: paving
    - get: paving-ci
    - get: pcf-releng-ci
    - get: srt-stemcell
      params:
        globs:
        - '*aws*.tgz'
        unpack: true
    - get: srt
      params:
        globs:
        - srt-*.pivotal
    - get: pks
      params:
        globs:
        - pivotal-container-service-*.pivotal
    - get: opsman-image
      params:
        globs:
        - '*aws*.yml'
    - get: platform-automation-image
      params:
        unpack: true
    - get: platform-automation-tasks
      params:
        unpack: true

  - do:

    - task: download-srt-stemcell
      file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
      input_mapping:
        ert-product: srt
      output_mapping:
        stemcell: stemcell-srt
      params:
        IAAS_TYPE: aws
        PIVNET_TOKEN: ((Shared-Paving Terraform/ci/pivnet_token/Notes))

    - task: download-pks-stemcell
      file: pcf-releng-ci/tasks/configuration/download-pivnet-stemcell/task.yml
      input_mapping:
        ert-product: pks
      output_mapping:
        stemcell: stemcell-pks
      params:
        IAAS_TYPE: aws
        PIVNET_TOKEN: ((Shared-Paving Terraform/ci/pivnet_token/Notes))

    - put: env-state-aws
      params:
        env_name: paving-aws
        terraform_source: paving/aws
        delete_on_failure: true

    - task: get-ops-manager-config
      file: paving-ci/ci/tasks/get-ops-manager-config/task.yml
      input_mapping:
        env-state: env-state-aws
        paving: paving-ci
      output_mapping:
        env-state: env-state-aws
      params:
        IAAS: aws

    - task: create-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/create-vm.yml
      input_mapping:
        image: opsman-image
        state: env-state-aws
      params:
        OPSMAN_CONFIG_FILE: ops-manager.yml
      on_failure:
        task: delete-vm
        image: platform-automation-image
        file: platform-automation-tasks/tasks/delete-vm.yml
        input_mapping:
          state: generated-state
        params:
          OPSMAN_CONFIG_FILE: ops-manager.yml

    - task: write-om-files
      file: paving-ci/ci/tasks/write-om-files/task.yml
      input_mapping:
        env-state: env-state-aws
      params:
        <<: *om-creds
        AUTH_CONFIG_FILE: paving-ci/ci/configuration/auth.yml
        ENV_YML: paving-ci/ci/configuration/env.yml
        DIRECTOR_CONFIG_PATH: paving-ci/ci/configuration/aws/director.yml
        SRT_CONFIG_FILE: paving-ci/ci/configuration/aws/srt.yml
        PKS_CONFIG_FILE: paving-ci/ci/configuration/aws/pks.yml

    - task: configure-authentication
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-authentication.yml

    - task: configure-director
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-director.yml

    - task: upload-srt-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        stemcell: stemcell-srt

    - task: upload-and-stage-srt
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      input_mapping:
        product: srt

    - task: configure-srt
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      params:
        CONFIG_FILE: srt.yml
      input_mapping:
        product: srt

    - task: upload-pks-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-stemcell.yml
      input_mapping:
        stemcell: stemcell-pks

    - task: upload-and-stage-pks
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      input_mapping:
        product: pks

    - task: configure-pks
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      params:
        CONFIG_FILE: pks.yml
      input_mapping:
        product: pks

    - task: apply-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-changes.yml

    - task: delete-installation
      image: platform-automation-image
      file: platform-automation-tasks/tasks/delete-installation.yml

    - task: delete-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/delete-vm.yml
      input_mapping:
        state: generated-state
      params:
        OPSMAN_CONFIG_FILE: ops-manager.yml

    - put: env-state-aws
      params:
        terraform_source: paving/aws
        env_name_file: env-state-aws/name
        delete_on_failure: true
        action: destroy
      get_params:
        action: destroy

- name: cleanup-aws
  serial: true
  public: false
  plan:
  - in_parallel:
    - get: paving-ci
    - get: paving
    - get: env-state-aws
  - do:
    - task: leftovers
      file: paving-ci/ci/tasks/leftovers/task.yml
      input_mapping:
        env-state: env-state-aws
      params:
        IAAS: aws
    - put: env-state-aws
      params:
        terraform_source: paving/aws
        env_name_file: env-state-aws/name
        delete_on_failure: true
        action: destroy
      get_params:
        action: destroy
